name: "Close stale issues"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v2.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. If this issue is still relevant please post a new comment or it will be closed in 5 days.'
        days-before-stale: 30
        days-before-close: 5
        stale-issue-label: 'stale'
        only-labels: 'question'
